apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  template:
    spec:
      containers:
        - name: node-app
          resources:
            limits:
              cpu: 0.5
              memory: 1Gi
            requests:
              cpu: 0.1
              memory: 64Mi