apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swimlane

resources:
  - ../../base/
  - config/mongodb-env.yaml

# We would love to use kustomize helm generator, but there still an open bug with OCI
# https://github.com/kubernetes-sigs/kustomize/issues/4381
# But we'll leave this here and stay with the manual route
# generators:
#   - mongodb-helm.yaml

patchesStrategicMerge:
  - patches/node-app-patch.yaml

images:
- name: node-app
  newName: bentomcfeeley/swim-node
  newTag: "0.1"