apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      micro-svc: node-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    spec:
      containers:
        - name: node-app
          image: node-app
          imagePullPolicy: Always
          env:
            - name: MONGODB_URL
              value: mongodb://$(MONGODB_USER):$(MONGODB_PASS)@mongodb.swimlane.svc.cluster.local:27017/$(MONGODB_DB)
          resources:
            limits:
              cpu: 0.5
              memory: 2Gi
            requests:
              cpu: 0.1
              memory: 64Mi
          ports:
            - containerPort: 3000
      terminationGracePeriodSeconds: 15
