apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  ports:
    - protocol: TCP
      port: 3000 # Service port 3000
      targetPort: 3000 # Forward traffic to port 3000 on pod
      name: http
